name: Metrics
on:
  schedule: [{cron: '0 0 1 * *'}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'byhow/byhow'"
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.README }}
          base: header, activity, community, repositories
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6
          plugin_languages_recent_load: 20
          plugin_languages_ignored: html, css, scss
